# Generated by Django 5.0.4 on 2024-04-27 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_phone_customuser_street'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('street', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('credit_card', models.TextField(blank=True)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(max_length=6)),
                ('birth_date', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
